### ISSUE TITLE
[docai-warehouse] Document properties of type `dateTimeValues` return error 'DateTime provided is invalid.'

### ISSUE THREAD

**Issue by snekcz** [GoogleCloudPlatform/document-ai-samples#701]
When I call `createDocument` function from Nodejs library and pass datetime `properties` in `document` object, the request returns an error: 
```
Error: 3 INVALID_ARGUMENT: DateTime provided is invalid.
    at callErrorFromStatus (/var/data/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/var/data/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/var/data/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/var/data/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /var/data/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/var/data/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/var/data/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /var/data/node_modules/@google-cloud/contentwarehouse/build/src/v1/document_service_client.js:203:29
    at /var/data/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at OngoingCallPromise.call (/var/data/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/var/data/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /var/data/node_modules/google-gax/build/src/createApiCall.js:84:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 3,
  details: 'DateTime provided is invalid.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```
My request's `properties` datetime values are:
 ```
...
{
    "name": "issue_date",
    "dateTimeValues": {
      "values": [
        {
          "year": 2023,
          "month": 6,
          "day": 7
        }
      ]
    }
  },
...
```
Which is according to documentation https://cloud.google.com/document-warehouse/docs/reference/rest/v1/Document#DateTime

**Comment by holtskinner** [comment]
From https://cloud.google.com/document-warehouse/docs/release-notes#January_16_2024

> Document AI Warehouse is deprecated and will no longer be available on Google Cloud after January 16, 2025. To safeguard your data, migrate any documents currently saved in Document AI Warehouse to an alternative like Cloud Storage. Ensure that your data migration is completed before the out of service date to prevent any data loss. See [Deprecations](https://cloud.google.com/document-warehouse/docs/deprecations/index) for details.
